name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-issue-message: 'This issue will soon be closed since issues in this project are mainly meant to be bugs or feature requests. Questions are directed to stackoverflow.'
          stale-issue-label: 'stale'
          days-before-stale: 7
          days-before-close: 1
          any-of-labels: question,needs-information,needs-mvc,needs information
